# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        exclude: >
          (?x)^(
              .*\.lock|.*\.csv|.*\.ipynb
          )$
        additional_dependencies:
        -   tomli
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    -   id: nbqa-black
    -   id: nbqa-isort
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   "types-requests"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.11"
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: ["--fix"]
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.21
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
    -   id: pyproject-fmt
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.0
    hooks:
    -   id: pre-commit-update
        args: ["--keep", "mdformat", "--keep", "pre-commit-update", "--keep", "cffconvert"]
-   repo: https://github.com/citation-file-format/cffconvert
    rev: b6045d78aac9e02b039703b030588d54d53262ac
    hooks:
    -   id: validate-cff
